package stardogrestapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"
	"github.com/Azure/go-autorest/autorest"
	"github.com/vshn/stardog-userrole-operator/stardogrest"
)

// BaseClientAPI contains the set of methods on the BaseClient type.
type BaseClientAPI interface {
	AddRole(ctx context.Context, userParameter string, role stardogrest.Rolename) (result autorest.Response, err error)
	AddRolePermission(ctx context.Context, role string, permission stardogrest.Permission) (result autorest.Response, err error)
	AddUserPermission(ctx context.Context, userParameter string, permission stardogrest.Permission) (result autorest.Response, err error)
	ChangePassword(ctx context.Context, userParameter string, password stardogrest.Password) (result autorest.Response, err error)
	CreateRole(ctx context.Context, role *stardogrest.Rolename) (result autorest.Response, err error)
	CreateUser(ctx context.Context, userParameter *stardogrest.User) (result autorest.Response, err error)
	IsEnabled(ctx context.Context, userParameter string) (result stardogrest.Enabled, err error)
	IsSuperuser(ctx context.Context, userParameter string) (result stardogrest.Superuser, err error)
	ListEffectivePermissions(ctx context.Context, userParameter string) (result stardogrest.Permissions, err error)
	ListRolePermissions(ctx context.Context, role string) (result stardogrest.Permissions, err error)
	ListRoles(ctx context.Context) (result stardogrest.Roles, err error)
	ListRoleUsers(ctx context.Context, role string) (result stardogrest.Users, err error)
	ListUserPermissions(ctx context.Context, userParameter string) (result stardogrest.Permissions, err error)
	ListUserRoles(ctx context.Context, userParameter string) (result stardogrest.Roles, err error)
	ListUsers(ctx context.Context) (result stardogrest.Users, err error)
	PutRoles(ctx context.Context, userParameter string, roles stardogrest.Roles) (result autorest.Response, err error)
	RemoveRole(ctx context.Context, userParameter string, role string) (result autorest.Response, err error)
	RemoveRole1(ctx context.Context, role string, force *bool) (result autorest.Response, err error)
	RemoveRolePermission(ctx context.Context, role string, permission stardogrest.Permission) (result autorest.Response, err error)
	RemoveUser(ctx context.Context, userParameter string) (result autorest.Response, err error)
	RemoveUserPermission(ctx context.Context, userParameter string, permission stardogrest.Permission) (result autorest.Response, err error)
	SetEnabled(ctx context.Context, userParameter string, enable stardogrest.Enabled) (result autorest.Response, err error)
	ValidateUser(ctx context.Context) (result autorest.Response, err error)
}

var _ BaseClientAPI = (*stardogrest.BaseClient)(nil)
