# permissions for end users to edit databasesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseset-editor-role
rules:
- apiGroups:
  - stardog.vshn.ch
  resources:
  - databasesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - databasesets/status
  verbs:
  - get
