---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - stardog.vshn.ch
  resources:
  - databases
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardoginstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardoginstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogusers/status
  verbs:
  - get
  - patch
  - update
