# permissions for end users to view stardogroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stardogrole-viewer-role
rules:
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogroles/status
  verbs:
  - get
