# permissions for end users to edit stardogroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stardogrole-editor-role
rules:
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogroles/status
  verbs:
  - get
