# permissions for end users to view stardoginstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stardoginstance-viewer-role
rules:
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardoginstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardoginstances/status
  verbs:
  - get
