# permissions for end users to view stardogusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stardoguser-viewer-role
rules:
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stardog.vshn.ch
  resources:
  - stardogusers/status
  verbs:
  - get
