// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Databases databases
//
// swagger:model Databases
type Databases struct {

	// databases
	// Required: true
	Databases []string `json:"databases"`
}

// Validate validates this databases
func (m *Databases) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDatabases(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Databases) validateDatabases(formats strfmt.Registry) error {

	if err := validate.Required("databases", "body", m.Databases); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this databases based on context it is used
func (m *Databases) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Databases) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Databases) UnmarshalBinary(b []byte) error {
	var res Databases
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
