// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Rolename rolename
//
// swagger:model Rolename
type Rolename struct {

	// rolename
	// Required: true
	Rolename *string `json:"rolename"`
}

// Validate validates this rolename
func (m *Rolename) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRolename(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Rolename) validateRolename(formats strfmt.Registry) error {

	if err := validate.Required("rolename", "body", m.Rolename); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this rolename based on context it is used
func (m *Rolename) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Rolename) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Rolename) UnmarshalBinary(b []byte) error {
	var res Rolename
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
