// Code generated by go-swagger; DO NOT EDIT.

package db

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateNewDatabaseReader is a Reader for the CreateNewDatabase structure.
type CreateNewDatabaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNewDatabaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateNewDatabaseCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateNewDatabaseBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /admin/databases] createNewDatabase", response, response.Code())
	}
}

// NewCreateNewDatabaseCreated creates a CreateNewDatabaseCreated with default headers values
func NewCreateNewDatabaseCreated() *CreateNewDatabaseCreated {
	return &CreateNewDatabaseCreated{}
}

/*
CreateNewDatabaseCreated describes a response with status code 201, with default header values.

Database created
*/
type CreateNewDatabaseCreated struct {
}

// IsSuccess returns true when this create new database created response has a 2xx status code
func (o *CreateNewDatabaseCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create new database created response has a 3xx status code
func (o *CreateNewDatabaseCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new database created response has a 4xx status code
func (o *CreateNewDatabaseCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create new database created response has a 5xx status code
func (o *CreateNewDatabaseCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create new database created response a status code equal to that given
func (o *CreateNewDatabaseCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create new database created response
func (o *CreateNewDatabaseCreated) Code() int {
	return 201
}

func (o *CreateNewDatabaseCreated) Error() string {
	return fmt.Sprintf("[POST /admin/databases][%d] createNewDatabaseCreated ", 201)
}

func (o *CreateNewDatabaseCreated) String() string {
	return fmt.Sprintf("[POST /admin/databases][%d] createNewDatabaseCreated ", 201)
}

func (o *CreateNewDatabaseCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateNewDatabaseBadRequest creates a CreateNewDatabaseBadRequest with default headers values
func NewCreateNewDatabaseBadRequest() *CreateNewDatabaseBadRequest {
	return &CreateNewDatabaseBadRequest{}
}

/*
CreateNewDatabaseBadRequest describes a response with status code 400, with default header values.

Invalid or malformed request body
*/
type CreateNewDatabaseBadRequest struct {
}

// IsSuccess returns true when this create new database bad request response has a 2xx status code
func (o *CreateNewDatabaseBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new database bad request response has a 3xx status code
func (o *CreateNewDatabaseBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new database bad request response has a 4xx status code
func (o *CreateNewDatabaseBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create new database bad request response has a 5xx status code
func (o *CreateNewDatabaseBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create new database bad request response a status code equal to that given
func (o *CreateNewDatabaseBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create new database bad request response
func (o *CreateNewDatabaseBadRequest) Code() int {
	return 400
}

func (o *CreateNewDatabaseBadRequest) Error() string {
	return fmt.Sprintf("[POST /admin/databases][%d] createNewDatabaseBadRequest ", 400)
}

func (o *CreateNewDatabaseBadRequest) String() string {
	return fmt.Sprintf("[POST /admin/databases][%d] createNewDatabaseBadRequest ", 400)
}

func (o *CreateNewDatabaseBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
