// Code generated by go-swagger; DO NOT EDIT.

package db

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// DropDatabaseReader is a Reader for the DropDatabase structure.
type DropDatabaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DropDatabaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDropDatabaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDropDatabaseNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDropDatabaseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDropDatabaseOK creates a DropDatabaseOK with default headers values
func NewDropDatabaseOK() *DropDatabaseOK {
	return &DropDatabaseOK{}
}

/*
DropDatabaseOK describes a response with status code 200, with default header values.

A dict containing an array of usernames
*/
type DropDatabaseOK struct {
	Payload *models.Generic
}

// IsSuccess returns true when this drop database o k response has a 2xx status code
func (o *DropDatabaseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this drop database o k response has a 3xx status code
func (o *DropDatabaseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this drop database o k response has a 4xx status code
func (o *DropDatabaseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this drop database o k response has a 5xx status code
func (o *DropDatabaseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this drop database o k response a status code equal to that given
func (o *DropDatabaseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the drop database o k response
func (o *DropDatabaseOK) Code() int {
	return 200
}

func (o *DropDatabaseOK) Error() string {
	return fmt.Sprintf("[DELETE /admin/databases/{db}][%d] dropDatabaseOK  %+v", 200, o.Payload)
}

func (o *DropDatabaseOK) String() string {
	return fmt.Sprintf("[DELETE /admin/databases/{db}][%d] dropDatabaseOK  %+v", 200, o.Payload)
}

func (o *DropDatabaseOK) GetPayload() *models.Generic {
	return o.Payload
}

func (o *DropDatabaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Generic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDropDatabaseNotFound creates a DropDatabaseNotFound with default headers values
func NewDropDatabaseNotFound() *DropDatabaseNotFound {
	return &DropDatabaseNotFound{}
}

/*
DropDatabaseNotFound describes a response with status code 404, with default header values.

Database does not exist
*/
type DropDatabaseNotFound struct {
	Payload *models.DBMissing
}

// IsSuccess returns true when this drop database not found response has a 2xx status code
func (o *DropDatabaseNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this drop database not found response has a 3xx status code
func (o *DropDatabaseNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this drop database not found response has a 4xx status code
func (o *DropDatabaseNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this drop database not found response has a 5xx status code
func (o *DropDatabaseNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this drop database not found response a status code equal to that given
func (o *DropDatabaseNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the drop database not found response
func (o *DropDatabaseNotFound) Code() int {
	return 404
}

func (o *DropDatabaseNotFound) Error() string {
	return fmt.Sprintf("[DELETE /admin/databases/{db}][%d] dropDatabaseNotFound  %+v", 404, o.Payload)
}

func (o *DropDatabaseNotFound) String() string {
	return fmt.Sprintf("[DELETE /admin/databases/{db}][%d] dropDatabaseNotFound  %+v", 404, o.Payload)
}

func (o *DropDatabaseNotFound) GetPayload() *models.DBMissing {
	return o.Payload
}

func (o *DropDatabaseNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DBMissing)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDropDatabaseDefault creates a DropDatabaseDefault with default headers values
func NewDropDatabaseDefault(code int) *DropDatabaseDefault {
	return &DropDatabaseDefault{
		_statusCode: code,
	}
}

/*
DropDatabaseDefault describes a response with status code -1, with default header values.

unexpected error
*/
type DropDatabaseDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this drop database default response has a 2xx status code
func (o *DropDatabaseDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this drop database default response has a 3xx status code
func (o *DropDatabaseDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this drop database default response has a 4xx status code
func (o *DropDatabaseDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this drop database default response has a 5xx status code
func (o *DropDatabaseDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this drop database default response a status code equal to that given
func (o *DropDatabaseDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the drop database default response
func (o *DropDatabaseDefault) Code() int {
	return o._statusCode
}

func (o *DropDatabaseDefault) Error() string {
	return fmt.Sprintf("[DELETE /admin/databases/{db}][%d] dropDatabase default  %+v", o._statusCode, o.Payload)
}

func (o *DropDatabaseDefault) String() string {
	return fmt.Sprintf("[DELETE /admin/databases/{db}][%d] dropDatabase default  %+v", o._statusCode, o.Payload)
}

func (o *DropDatabaseDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DropDatabaseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
