// Code generated by go-swagger; DO NOT EDIT.

package db

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// GetDBSizeReader is a Reader for the GetDBSize structure.
type GetDBSizeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDBSizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDBSizeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDBSizeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /{db}/size] getDBSize", response, response.Code())
	}
}

// NewGetDBSizeOK creates a GetDBSizeOK with default headers values
func NewGetDBSizeOK() *GetDBSizeOK {
	return &GetDBSizeOK{}
}

/*
GetDBSizeOK describes a response with status code 200, with default header values.

The size (in triples) of the database
*/
type GetDBSizeOK struct {
	Payload string
}

// IsSuccess returns true when this get d b size o k response has a 2xx status code
func (o *GetDBSizeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get d b size o k response has a 3xx status code
func (o *GetDBSizeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get d b size o k response has a 4xx status code
func (o *GetDBSizeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get d b size o k response has a 5xx status code
func (o *GetDBSizeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get d b size o k response a status code equal to that given
func (o *GetDBSizeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get d b size o k response
func (o *GetDBSizeOK) Code() int {
	return 200
}

func (o *GetDBSizeOK) Error() string {
	return fmt.Sprintf("[GET /{db}/size][%d] getDBSizeOK  %+v", 200, o.Payload)
}

func (o *GetDBSizeOK) String() string {
	return fmt.Sprintf("[GET /{db}/size][%d] getDBSizeOK  %+v", 200, o.Payload)
}

func (o *GetDBSizeOK) GetPayload() string {
	return o.Payload
}

func (o *GetDBSizeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDBSizeNotFound creates a GetDBSizeNotFound with default headers values
func NewGetDBSizeNotFound() *GetDBSizeNotFound {
	return &GetDBSizeNotFound{}
}

/*
GetDBSizeNotFound describes a response with status code 404, with default header values.

Database does not exist
*/
type GetDBSizeNotFound struct {
	Payload *models.NotExists
}

// IsSuccess returns true when this get d b size not found response has a 2xx status code
func (o *GetDBSizeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get d b size not found response has a 3xx status code
func (o *GetDBSizeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get d b size not found response has a 4xx status code
func (o *GetDBSizeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get d b size not found response has a 5xx status code
func (o *GetDBSizeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get d b size not found response a status code equal to that given
func (o *GetDBSizeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get d b size not found response
func (o *GetDBSizeNotFound) Code() int {
	return 404
}

func (o *GetDBSizeNotFound) Error() string {
	return fmt.Sprintf("[GET /{db}/size][%d] getDBSizeNotFound  %+v", 404, o.Payload)
}

func (o *GetDBSizeNotFound) String() string {
	return fmt.Sprintf("[GET /{db}/size][%d] getDBSizeNotFound  %+v", 404, o.Payload)
}

func (o *GetDBSizeNotFound) GetPayload() *models.NotExists {
	return o.Payload
}

func (o *GetDBSizeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotExists)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
