// Code generated by go-swagger; DO NOT EDIT.

package db

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// ListDatabasesReader is a Reader for the ListDatabases structure.
type ListDatabasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDatabasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDatabasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /admin/databases] listDatabases", response, response.Code())
	}
}

// NewListDatabasesOK creates a ListDatabasesOK with default headers values
func NewListDatabasesOK() *ListDatabasesOK {
	return &ListDatabasesOK{}
}

/*
ListDatabasesOK describes a response with status code 200, with default header values.

Operation successful
*/
type ListDatabasesOK struct {
	Payload *models.Databases
}

// IsSuccess returns true when this list databases o k response has a 2xx status code
func (o *ListDatabasesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list databases o k response has a 3xx status code
func (o *ListDatabasesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list databases o k response has a 4xx status code
func (o *ListDatabasesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list databases o k response has a 5xx status code
func (o *ListDatabasesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list databases o k response a status code equal to that given
func (o *ListDatabasesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list databases o k response
func (o *ListDatabasesOK) Code() int {
	return 200
}

func (o *ListDatabasesOK) Error() string {
	return fmt.Sprintf("[GET /admin/databases][%d] listDatabasesOK  %+v", 200, o.Payload)
}

func (o *ListDatabasesOK) String() string {
	return fmt.Sprintf("[GET /admin/databases][%d] listDatabasesOK  %+v", 200, o.Payload)
}

func (o *ListDatabasesOK) GetPayload() *models.Databases {
	return o.Payload
}

func (o *ListDatabasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Databases)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
