// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIsEnabledParams creates a new IsEnabledParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIsEnabledParams() *IsEnabledParams {
	return &IsEnabledParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIsEnabledParamsWithTimeout creates a new IsEnabledParams object
// with the ability to set a timeout on a request.
func NewIsEnabledParamsWithTimeout(timeout time.Duration) *IsEnabledParams {
	return &IsEnabledParams{
		timeout: timeout,
	}
}

// NewIsEnabledParamsWithContext creates a new IsEnabledParams object
// with the ability to set a context for a request.
func NewIsEnabledParamsWithContext(ctx context.Context) *IsEnabledParams {
	return &IsEnabledParams{
		Context: ctx,
	}
}

// NewIsEnabledParamsWithHTTPClient creates a new IsEnabledParams object
// with the ability to set a custom HTTPClient for a request.
func NewIsEnabledParamsWithHTTPClient(client *http.Client) *IsEnabledParams {
	return &IsEnabledParams{
		HTTPClient: client,
	}
}

/*
IsEnabledParams contains all the parameters to send to the API endpoint

	for the is enabled operation.

	Typically these are written to a http.Request.
*/
type IsEnabledParams struct {

	/* User.

	   The username of the user whose status should be queried
	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the is enabled params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IsEnabledParams) WithDefaults() *IsEnabledParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the is enabled params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IsEnabledParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the is enabled params
func (o *IsEnabledParams) WithTimeout(timeout time.Duration) *IsEnabledParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the is enabled params
func (o *IsEnabledParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the is enabled params
func (o *IsEnabledParams) WithContext(ctx context.Context) *IsEnabledParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the is enabled params
func (o *IsEnabledParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the is enabled params
func (o *IsEnabledParams) WithHTTPClient(client *http.Client) *IsEnabledParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the is enabled params
func (o *IsEnabledParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the is enabled params
func (o *IsEnabledParams) WithUser(user string) *IsEnabledParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the is enabled params
func (o *IsEnabledParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *IsEnabledParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
