// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// IsSuperuserReader is a Reader for the IsSuperuser structure.
type IsSuperuserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IsSuperuserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIsSuperuserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIsSuperuserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIsSuperuserOK creates a IsSuperuserOK with default headers values
func NewIsSuperuserOK() *IsSuperuserOK {
	return &IsSuperuserOK{}
}

/*
IsSuperuserOK describes a response with status code 200, with default header values.

The user's superuser status
*/
type IsSuperuserOK struct {
	Payload *models.Superuser
}

// IsSuccess returns true when this is superuser o k response has a 2xx status code
func (o *IsSuperuserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this is superuser o k response has a 3xx status code
func (o *IsSuperuserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this is superuser o k response has a 4xx status code
func (o *IsSuperuserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this is superuser o k response has a 5xx status code
func (o *IsSuperuserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this is superuser o k response a status code equal to that given
func (o *IsSuperuserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the is superuser o k response
func (o *IsSuperuserOK) Code() int {
	return 200
}

func (o *IsSuperuserOK) Error() string {
	return fmt.Sprintf("[GET /admin/users/{user}/superuser][%d] isSuperuserOK  %+v", 200, o.Payload)
}

func (o *IsSuperuserOK) String() string {
	return fmt.Sprintf("[GET /admin/users/{user}/superuser][%d] isSuperuserOK  %+v", 200, o.Payload)
}

func (o *IsSuperuserOK) GetPayload() *models.Superuser {
	return o.Payload
}

func (o *IsSuperuserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Superuser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIsSuperuserDefault creates a IsSuperuserDefault with default headers values
func NewIsSuperuserDefault(code int) *IsSuperuserDefault {
	return &IsSuperuserDefault{
		_statusCode: code,
	}
}

/*
IsSuperuserDefault describes a response with status code -1, with default header values.

unexpected error
*/
type IsSuperuserDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this is superuser default response has a 2xx status code
func (o *IsSuperuserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this is superuser default response has a 3xx status code
func (o *IsSuperuserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this is superuser default response has a 4xx status code
func (o *IsSuperuserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this is superuser default response has a 5xx status code
func (o *IsSuperuserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this is superuser default response a status code equal to that given
func (o *IsSuperuserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the is superuser default response
func (o *IsSuperuserDefault) Code() int {
	return o._statusCode
}

func (o *IsSuperuserDefault) Error() string {
	return fmt.Sprintf("[GET /admin/users/{user}/superuser][%d] isSuperuser default  %+v", o._statusCode, o.Payload)
}

func (o *IsSuperuserDefault) String() string {
	return fmt.Sprintf("[GET /admin/users/{user}/superuser][%d] isSuperuser default  %+v", o._statusCode, o.Payload)
}

func (o *IsSuperuserDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *IsSuperuserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
