// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// ListUsersReader is a Reader for the ListUsers structure.
type ListUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListUsersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListUsersOK creates a ListUsersOK with default headers values
func NewListUsersOK() *ListUsersOK {
	return &ListUsersOK{}
}

/*
ListUsersOK describes a response with status code 200, with default header values.

A dict containing an array of usernames
*/
type ListUsersOK struct {
	Payload *models.Users
}

// IsSuccess returns true when this list users o k response has a 2xx status code
func (o *ListUsersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list users o k response has a 3xx status code
func (o *ListUsersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list users o k response has a 4xx status code
func (o *ListUsersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list users o k response has a 5xx status code
func (o *ListUsersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list users o k response a status code equal to that given
func (o *ListUsersOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListUsersOK) Error() string {
	return fmt.Sprintf("[GET /users][%d] listUsersOK  %+v", 200, o.Payload)
}

func (o *ListUsersOK) String() string {
	return fmt.Sprintf("[GET /users][%d] listUsersOK  %+v", 200, o.Payload)
}

func (o *ListUsersOK) GetPayload() *models.Users {
	return o.Payload
}

func (o *ListUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Users)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListUsersDefault creates a ListUsersDefault with default headers values
func NewListUsersDefault(code int) *ListUsersDefault {
	return &ListUsersDefault{
		_statusCode: code,
	}
}

/*
ListUsersDefault describes a response with status code -1, with default header values.

unexpected error
*/
type ListUsersDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list users default response
func (o *ListUsersDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list users default response has a 2xx status code
func (o *ListUsersDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list users default response has a 3xx status code
func (o *ListUsersDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list users default response has a 4xx status code
func (o *ListUsersDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list users default response has a 5xx status code
func (o *ListUsersDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list users default response a status code equal to that given
func (o *ListUsersDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListUsersDefault) Error() string {
	return fmt.Sprintf("[GET /users][%d] listUsers default  %+v", o._statusCode, o.Payload)
}

func (o *ListUsersDefault) String() string {
	return fmt.Sprintf("[GET /users][%d] listUsers default  %+v", o._statusCode, o.Payload)
}

func (o *ListUsersDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListUsersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
