// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewValidateUserParams creates a new ValidateUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewValidateUserParams() *ValidateUserParams {
	return &ValidateUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewValidateUserParamsWithTimeout creates a new ValidateUserParams object
// with the ability to set a timeout on a request.
func NewValidateUserParamsWithTimeout(timeout time.Duration) *ValidateUserParams {
	return &ValidateUserParams{
		timeout: timeout,
	}
}

// NewValidateUserParamsWithContext creates a new ValidateUserParams object
// with the ability to set a context for a request.
func NewValidateUserParamsWithContext(ctx context.Context) *ValidateUserParams {
	return &ValidateUserParams{
		Context: ctx,
	}
}

// NewValidateUserParamsWithHTTPClient creates a new ValidateUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewValidateUserParamsWithHTTPClient(client *http.Client) *ValidateUserParams {
	return &ValidateUserParams{
		HTTPClient: client,
	}
}

/*
ValidateUserParams contains all the parameters to send to the API endpoint

	for the validate user operation.

	Typically these are written to a http.Request.
*/
type ValidateUserParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the validate user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateUserParams) WithDefaults() *ValidateUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the validate user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the validate user params
func (o *ValidateUserParams) WithTimeout(timeout time.Duration) *ValidateUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate user params
func (o *ValidateUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate user params
func (o *ValidateUserParams) WithContext(ctx context.Context) *ValidateUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate user params
func (o *ValidateUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate user params
func (o *ValidateUserParams) WithHTTPClient(client *http.Client) *ValidateUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate user params
func (o *ValidateUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
