// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// ValidateUserReader is a Reader for the ValidateUser structure.
type ValidateUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewValidateUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewValidateUserOK creates a ValidateUserOK with default headers values
func NewValidateUserOK() *ValidateUserOK {
	return &ValidateUserOK{}
}

/*
ValidateUserOK describes a response with status code 200, with default header values.

Null response
*/
type ValidateUserOK struct {
}

// IsSuccess returns true when this validate user o k response has a 2xx status code
func (o *ValidateUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this validate user o k response has a 3xx status code
func (o *ValidateUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this validate user o k response has a 4xx status code
func (o *ValidateUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this validate user o k response has a 5xx status code
func (o *ValidateUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this validate user o k response a status code equal to that given
func (o *ValidateUserOK) IsCode(code int) bool {
	return code == 200
}

func (o *ValidateUserOK) Error() string {
	return fmt.Sprintf("[GET /users/valid][%d] validateUserOK ", 200)
}

func (o *ValidateUserOK) String() string {
	return fmt.Sprintf("[GET /users/valid][%d] validateUserOK ", 200)
}

func (o *ValidateUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateUserDefault creates a ValidateUserDefault with default headers values
func NewValidateUserDefault(code int) *ValidateUserDefault {
	return &ValidateUserDefault{
		_statusCode: code,
	}
}

/*
ValidateUserDefault describes a response with status code -1, with default header values.

User invalid
*/
type ValidateUserDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the validate user default response
func (o *ValidateUserDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this validate user default response has a 2xx status code
func (o *ValidateUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this validate user default response has a 3xx status code
func (o *ValidateUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this validate user default response has a 4xx status code
func (o *ValidateUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this validate user default response has a 5xx status code
func (o *ValidateUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this validate user default response a status code equal to that given
func (o *ValidateUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ValidateUserDefault) Error() string {
	return fmt.Sprintf("[GET /users/valid][%d] validateUser default  %+v", o._statusCode, o.Payload)
}

func (o *ValidateUserDefault) String() string {
	return fmt.Sprintf("[GET /users/valid][%d] validateUser default  %+v", o._statusCode, o.Payload)
}

func (o *ValidateUserDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ValidateUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
