// Code generated by go-swagger; DO NOT EDIT.

package users_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListRoleUsersParams creates a new ListRoleUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListRoleUsersParams() *ListRoleUsersParams {
	return &ListRoleUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListRoleUsersParamsWithTimeout creates a new ListRoleUsersParams object
// with the ability to set a timeout on a request.
func NewListRoleUsersParamsWithTimeout(timeout time.Duration) *ListRoleUsersParams {
	return &ListRoleUsersParams{
		timeout: timeout,
	}
}

// NewListRoleUsersParamsWithContext creates a new ListRoleUsersParams object
// with the ability to set a context for a request.
func NewListRoleUsersParamsWithContext(ctx context.Context) *ListRoleUsersParams {
	return &ListRoleUsersParams{
		Context: ctx,
	}
}

// NewListRoleUsersParamsWithHTTPClient creates a new ListRoleUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewListRoleUsersParamsWithHTTPClient(client *http.Client) *ListRoleUsersParams {
	return &ListRoleUsersParams{
		HTTPClient: client,
	}
}

/*
ListRoleUsersParams contains all the parameters to send to the API endpoint

	for the list role users operation.

	Typically these are written to a http.Request.
*/
type ListRoleUsersParams struct {

	/* Role.

	   The role name of the role whose users should be listed
	*/
	Role string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list role users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRoleUsersParams) WithDefaults() *ListRoleUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list role users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRoleUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list role users params
func (o *ListRoleUsersParams) WithTimeout(timeout time.Duration) *ListRoleUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list role users params
func (o *ListRoleUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list role users params
func (o *ListRoleUsersParams) WithContext(ctx context.Context) *ListRoleUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list role users params
func (o *ListRoleUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list role users params
func (o *ListRoleUsersParams) WithHTTPClient(client *http.Client) *ListRoleUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list role users params
func (o *ListRoleUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRole adds the role to the list role users params
func (o *ListRoleUsersParams) WithRole(role string) *ListRoleUsersParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the list role users params
func (o *ListRoleUsersParams) SetRole(role string) {
	o.Role = role
}

// WriteToRequest writes these params to a swagger request
func (o *ListRoleUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
