// Code generated by go-swagger; DO NOT EDIT.

package users_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// ListUserRolesReader is a Reader for the ListUserRoles structure.
type ListUserRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListUserRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListUserRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListUserRolesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListUserRolesOK creates a ListUserRolesOK with default headers values
func NewListUserRolesOK() *ListUserRolesOK {
	return &ListUserRolesOK{}
}

/*
ListUserRolesOK describes a response with status code 200, with default header values.

The user's roles
*/
type ListUserRolesOK struct {
	Payload *models.Roles
}

// IsSuccess returns true when this list user roles o k response has a 2xx status code
func (o *ListUserRolesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list user roles o k response has a 3xx status code
func (o *ListUserRolesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list user roles o k response has a 4xx status code
func (o *ListUserRolesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list user roles o k response has a 5xx status code
func (o *ListUserRolesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list user roles o k response a status code equal to that given
func (o *ListUserRolesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list user roles o k response
func (o *ListUserRolesOK) Code() int {
	return 200
}

func (o *ListUserRolesOK) Error() string {
	return fmt.Sprintf("[GET /users/{user}/roles][%d] listUserRolesOK  %+v", 200, o.Payload)
}

func (o *ListUserRolesOK) String() string {
	return fmt.Sprintf("[GET /users/{user}/roles][%d] listUserRolesOK  %+v", 200, o.Payload)
}

func (o *ListUserRolesOK) GetPayload() *models.Roles {
	return o.Payload
}

func (o *ListUserRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Roles)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListUserRolesDefault creates a ListUserRolesDefault with default headers values
func NewListUserRolesDefault(code int) *ListUserRolesDefault {
	return &ListUserRolesDefault{
		_statusCode: code,
	}
}

/*
ListUserRolesDefault describes a response with status code -1, with default header values.

unexpected error
*/
type ListUserRolesDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this list user roles default response has a 2xx status code
func (o *ListUserRolesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list user roles default response has a 3xx status code
func (o *ListUserRolesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list user roles default response has a 4xx status code
func (o *ListUserRolesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list user roles default response has a 5xx status code
func (o *ListUserRolesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list user roles default response a status code equal to that given
func (o *ListUserRolesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list user roles default response
func (o *ListUserRolesDefault) Code() int {
	return o._statusCode
}

func (o *ListUserRolesDefault) Error() string {
	return fmt.Sprintf("[GET /users/{user}/roles][%d] listUserRoles default  %+v", o._statusCode, o.Payload)
}

func (o *ListUserRolesDefault) String() string {
	return fmt.Sprintf("[GET /users/{user}/roles][%d] listUserRoles default  %+v", o._statusCode, o.Payload)
}

func (o *ListUserRolesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListUserRolesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
