// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// RemoveRoleReader is a Reader for the RemoveRole structure.
type RemoveRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRemoveRoleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRemoveRoleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRemoveRoleNoContent creates a RemoveRoleNoContent with default headers values
func NewRemoveRoleNoContent() *RemoveRoleNoContent {
	return &RemoveRoleNoContent{}
}

/*
RemoveRoleNoContent describes a response with status code 204, with default header values.

Null response
*/
type RemoveRoleNoContent struct {
}

// IsSuccess returns true when this remove role no content response has a 2xx status code
func (o *RemoveRoleNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove role no content response has a 3xx status code
func (o *RemoveRoleNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove role no content response has a 4xx status code
func (o *RemoveRoleNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove role no content response has a 5xx status code
func (o *RemoveRoleNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this remove role no content response a status code equal to that given
func (o *RemoveRoleNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the remove role no content response
func (o *RemoveRoleNoContent) Code() int {
	return 204
}

func (o *RemoveRoleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /admin/roles/{role}][%d] removeRoleNoContent ", 204)
}

func (o *RemoveRoleNoContent) String() string {
	return fmt.Sprintf("[DELETE /admin/roles/{role}][%d] removeRoleNoContent ", 204)
}

func (o *RemoveRoleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveRoleDefault creates a RemoveRoleDefault with default headers values
func NewRemoveRoleDefault(code int) *RemoveRoleDefault {
	return &RemoveRoleDefault{
		_statusCode: code,
	}
}

/*
RemoveRoleDefault describes a response with status code -1, with default header values.

unexpected error
*/
type RemoveRoleDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this remove role default response has a 2xx status code
func (o *RemoveRoleDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this remove role default response has a 3xx status code
func (o *RemoveRoleDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this remove role default response has a 4xx status code
func (o *RemoveRoleDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this remove role default response has a 5xx status code
func (o *RemoveRoleDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this remove role default response a status code equal to that given
func (o *RemoveRoleDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the remove role default response
func (o *RemoveRoleDefault) Code() int {
	return o._statusCode
}

func (o *RemoveRoleDefault) Error() string {
	return fmt.Sprintf("[DELETE /admin/roles/{role}][%d] removeRole default  %+v", o._statusCode, o.Payload)
}

func (o *RemoveRoleDefault) String() string {
	return fmt.Sprintf("[DELETE /admin/roles/{role}][%d] removeRole default  %+v", o._statusCode, o.Payload)
}

func (o *RemoveRoleDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *RemoveRoleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
