// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRemoveRoleParams creates a new RemoveRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveRoleParams() *RemoveRoleParams {
	return &RemoveRoleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveRoleParamsWithTimeout creates a new RemoveRoleParams object
// with the ability to set a timeout on a request.
func NewRemoveRoleParamsWithTimeout(timeout time.Duration) *RemoveRoleParams {
	return &RemoveRoleParams{
		timeout: timeout,
	}
}

// NewRemoveRoleParamsWithContext creates a new RemoveRoleParams object
// with the ability to set a context for a request.
func NewRemoveRoleParamsWithContext(ctx context.Context) *RemoveRoleParams {
	return &RemoveRoleParams{
		Context: ctx,
	}
}

// NewRemoveRoleParamsWithHTTPClient creates a new RemoveRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveRoleParamsWithHTTPClient(client *http.Client) *RemoveRoleParams {
	return &RemoveRoleParams{
		HTTPClient: client,
	}
}

/*
RemoveRoleParams contains all the parameters to send to the API endpoint

	for the remove role operation.

	Typically these are written to a http.Request.
*/
type RemoveRoleParams struct {

	/* Force.

	   Whether to delete even if in use

	   Default: true
	*/
	Force *bool

	/* Role.

	   The name of the role to delete
	*/
	Role string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveRoleParams) WithDefaults() *RemoveRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveRoleParams) SetDefaults() {
	var (
		forceDefault = bool(true)
	)

	val := RemoveRoleParams{
		Force: &forceDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the remove role params
func (o *RemoveRoleParams) WithTimeout(timeout time.Duration) *RemoveRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove role params
func (o *RemoveRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove role params
func (o *RemoveRoleParams) WithContext(ctx context.Context) *RemoveRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove role params
func (o *RemoveRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove role params
func (o *RemoveRoleParams) WithHTTPClient(client *http.Client) *RemoveRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove role params
func (o *RemoveRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForce adds the force to the remove role params
func (o *RemoveRoleParams) WithForce(force *bool) *RemoveRoleParams {
	o.SetForce(force)
	return o
}

// SetForce adds the force to the remove role params
func (o *RemoveRoleParams) SetForce(force *bool) {
	o.Force = force
}

// WithRole adds the role to the remove role params
func (o *RemoveRoleParams) WithRole(role string) *RemoveRoleParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the remove role params
func (o *RemoveRoleParams) SetRole(role string) {
	o.Role = role
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Force != nil {

		// query param force
		var qrForce bool

		if o.Force != nil {
			qrForce = *o.Force
		}
		qForce := swag.FormatBool(qrForce)
		if qForce != "" {

			if err := r.SetQueryParam("force", qForce); err != nil {
				return err
			}
		}
	}

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
