// Code generated by go-swagger; DO NOT EDIT.

package roles_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListRolePermissionsParams creates a new ListRolePermissionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListRolePermissionsParams() *ListRolePermissionsParams {
	return &ListRolePermissionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListRolePermissionsParamsWithTimeout creates a new ListRolePermissionsParams object
// with the ability to set a timeout on a request.
func NewListRolePermissionsParamsWithTimeout(timeout time.Duration) *ListRolePermissionsParams {
	return &ListRolePermissionsParams{
		timeout: timeout,
	}
}

// NewListRolePermissionsParamsWithContext creates a new ListRolePermissionsParams object
// with the ability to set a context for a request.
func NewListRolePermissionsParamsWithContext(ctx context.Context) *ListRolePermissionsParams {
	return &ListRolePermissionsParams{
		Context: ctx,
	}
}

// NewListRolePermissionsParamsWithHTTPClient creates a new ListRolePermissionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListRolePermissionsParamsWithHTTPClient(client *http.Client) *ListRolePermissionsParams {
	return &ListRolePermissionsParams{
		HTTPClient: client,
	}
}

/*
ListRolePermissionsParams contains all the parameters to send to the API endpoint

	for the list role permissions operation.

	Typically these are written to a http.Request.
*/
type ListRolePermissionsParams struct {

	/* Role.

	   The name of the role whose permissions should be listed
	*/
	Role string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list role permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRolePermissionsParams) WithDefaults() *ListRolePermissionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list role permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRolePermissionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list role permissions params
func (o *ListRolePermissionsParams) WithTimeout(timeout time.Duration) *ListRolePermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list role permissions params
func (o *ListRolePermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list role permissions params
func (o *ListRolePermissionsParams) WithContext(ctx context.Context) *ListRolePermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list role permissions params
func (o *ListRolePermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list role permissions params
func (o *ListRolePermissionsParams) WithHTTPClient(client *http.Client) *ListRolePermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list role permissions params
func (o *ListRolePermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRole adds the role to the list role permissions params
func (o *ListRolePermissionsParams) WithRole(role string) *ListRolePermissionsParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the list role permissions params
func (o *ListRolePermissionsParams) SetRole(role string) {
	o.Role = role
}

// WriteToRequest writes these params to a swagger request
func (o *ListRolePermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
