// Code generated by go-swagger; DO NOT EDIT.

package roles_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// NewRemoveRolePermissionParams creates a new RemoveRolePermissionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveRolePermissionParams() *RemoveRolePermissionParams {
	return &RemoveRolePermissionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveRolePermissionParamsWithTimeout creates a new RemoveRolePermissionParams object
// with the ability to set a timeout on a request.
func NewRemoveRolePermissionParamsWithTimeout(timeout time.Duration) *RemoveRolePermissionParams {
	return &RemoveRolePermissionParams{
		timeout: timeout,
	}
}

// NewRemoveRolePermissionParamsWithContext creates a new RemoveRolePermissionParams object
// with the ability to set a context for a request.
func NewRemoveRolePermissionParamsWithContext(ctx context.Context) *RemoveRolePermissionParams {
	return &RemoveRolePermissionParams{
		Context: ctx,
	}
}

// NewRemoveRolePermissionParamsWithHTTPClient creates a new RemoveRolePermissionParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveRolePermissionParamsWithHTTPClient(client *http.Client) *RemoveRolePermissionParams {
	return &RemoveRolePermissionParams{
		HTTPClient: client,
	}
}

/*
RemoveRolePermissionParams contains all the parameters to send to the API endpoint

	for the remove role permission operation.

	Typically these are written to a http.Request.
*/
type RemoveRolePermissionParams struct {

	/* Permission.

	   The permission to remove
	*/
	Permission *models.Permission

	/* Role.

	   The role to remove the permission from
	*/
	Role string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove role permission params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveRolePermissionParams) WithDefaults() *RemoveRolePermissionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove role permission params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveRolePermissionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove role permission params
func (o *RemoveRolePermissionParams) WithTimeout(timeout time.Duration) *RemoveRolePermissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove role permission params
func (o *RemoveRolePermissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove role permission params
func (o *RemoveRolePermissionParams) WithContext(ctx context.Context) *RemoveRolePermissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove role permission params
func (o *RemoveRolePermissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove role permission params
func (o *RemoveRolePermissionParams) WithHTTPClient(client *http.Client) *RemoveRolePermissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove role permission params
func (o *RemoveRolePermissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPermission adds the permission to the remove role permission params
func (o *RemoveRolePermissionParams) WithPermission(permission *models.Permission) *RemoveRolePermissionParams {
	o.SetPermission(permission)
	return o
}

// SetPermission adds the permission to the remove role permission params
func (o *RemoveRolePermissionParams) SetPermission(permission *models.Permission) {
	o.Permission = permission
}

// WithRole adds the role to the remove role permission params
func (o *RemoveRolePermissionParams) WithRole(role string) *RemoveRolePermissionParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the remove role permission params
func (o *RemoveRolePermissionParams) SetRole(role string) {
	o.Role = role
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveRolePermissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Permission != nil {
		if err := r.SetBodyParam(o.Permission); err != nil {
			return err
		}
	}

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
