// Code generated by go-swagger; DO NOT EDIT.

package roles_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new roles permissions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for roles permissions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AddRolePermission(params *AddRolePermissionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddRolePermissionCreated, error)

	ListRolePermissions(params *ListRolePermissionsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListRolePermissionsOK, error)

	RemoveRolePermission(params *RemoveRolePermissionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveRolePermissionCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
AddRolePermission adds a permission to a role
*/
func (a *Client) AddRolePermission(params *AddRolePermissionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddRolePermissionCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddRolePermissionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "addRolePermission",
		Method:             "PUT",
		PathPattern:        "/permissions/role/{role}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AddRolePermissionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddRolePermissionCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AddRolePermissionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListRolePermissions lists the role s permissions
*/
func (a *Client) ListRolePermissions(params *ListRolePermissionsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListRolePermissionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListRolePermissionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listRolePermissions",
		Method:             "GET",
		PathPattern:        "/permissions/role/{role}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListRolePermissionsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListRolePermissionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListRolePermissionsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
RemoveRolePermission removes a permission from a role
*/
func (a *Client) RemoveRolePermission(params *RemoveRolePermissionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveRolePermissionCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRemoveRolePermissionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "removeRolePermission",
		Method:             "POST",
		PathPattern:        "/permissions/role/{role}/delete",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &RemoveRolePermissionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RemoveRolePermissionCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*RemoveRolePermissionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
