// Code generated by go-swagger; DO NOT EDIT.

package users_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// AddUserPermissionReader is a Reader for the AddUserPermission structure.
type AddUserPermissionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddUserPermissionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddUserPermissionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAddUserPermissionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAddUserPermissionCreated creates a AddUserPermissionCreated with default headers values
func NewAddUserPermissionCreated() *AddUserPermissionCreated {
	return &AddUserPermissionCreated{}
}

/*
AddUserPermissionCreated describes a response with status code 201, with default header values.

Null response
*/
type AddUserPermissionCreated struct {
}

// IsSuccess returns true when this add user permission created response has a 2xx status code
func (o *AddUserPermissionCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add user permission created response has a 3xx status code
func (o *AddUserPermissionCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add user permission created response has a 4xx status code
func (o *AddUserPermissionCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this add user permission created response has a 5xx status code
func (o *AddUserPermissionCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this add user permission created response a status code equal to that given
func (o *AddUserPermissionCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the add user permission created response
func (o *AddUserPermissionCreated) Code() int {
	return 201
}

func (o *AddUserPermissionCreated) Error() string {
	return fmt.Sprintf("[PUT /permissions/user/{user}][%d] addUserPermissionCreated ", 201)
}

func (o *AddUserPermissionCreated) String() string {
	return fmt.Sprintf("[PUT /permissions/user/{user}][%d] addUserPermissionCreated ", 201)
}

func (o *AddUserPermissionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddUserPermissionDefault creates a AddUserPermissionDefault with default headers values
func NewAddUserPermissionDefault(code int) *AddUserPermissionDefault {
	return &AddUserPermissionDefault{
		_statusCode: code,
	}
}

/*
AddUserPermissionDefault describes a response with status code -1, with default header values.

unexpected error
*/
type AddUserPermissionDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this add user permission default response has a 2xx status code
func (o *AddUserPermissionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this add user permission default response has a 3xx status code
func (o *AddUserPermissionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this add user permission default response has a 4xx status code
func (o *AddUserPermissionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this add user permission default response has a 5xx status code
func (o *AddUserPermissionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this add user permission default response a status code equal to that given
func (o *AddUserPermissionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the add user permission default response
func (o *AddUserPermissionDefault) Code() int {
	return o._statusCode
}

func (o *AddUserPermissionDefault) Error() string {
	return fmt.Sprintf("[PUT /permissions/user/{user}][%d] addUserPermission default  %+v", o._statusCode, o.Payload)
}

func (o *AddUserPermissionDefault) String() string {
	return fmt.Sprintf("[PUT /permissions/user/{user}][%d] addUserPermission default  %+v", o._statusCode, o.Payload)
}

func (o *AddUserPermissionDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddUserPermissionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
