// Code generated by go-swagger; DO NOT EDIT.

package users_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListEffectivePermissionsParams creates a new ListEffectivePermissionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListEffectivePermissionsParams() *ListEffectivePermissionsParams {
	return &ListEffectivePermissionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListEffectivePermissionsParamsWithTimeout creates a new ListEffectivePermissionsParams object
// with the ability to set a timeout on a request.
func NewListEffectivePermissionsParamsWithTimeout(timeout time.Duration) *ListEffectivePermissionsParams {
	return &ListEffectivePermissionsParams{
		timeout: timeout,
	}
}

// NewListEffectivePermissionsParamsWithContext creates a new ListEffectivePermissionsParams object
// with the ability to set a context for a request.
func NewListEffectivePermissionsParamsWithContext(ctx context.Context) *ListEffectivePermissionsParams {
	return &ListEffectivePermissionsParams{
		Context: ctx,
	}
}

// NewListEffectivePermissionsParamsWithHTTPClient creates a new ListEffectivePermissionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListEffectivePermissionsParamsWithHTTPClient(client *http.Client) *ListEffectivePermissionsParams {
	return &ListEffectivePermissionsParams{
		HTTPClient: client,
	}
}

/*
ListEffectivePermissionsParams contains all the parameters to send to the API endpoint

	for the list effective permissions operation.

	Typically these are written to a http.Request.
*/
type ListEffectivePermissionsParams struct {

	/* User.

	   The name of the user whose permissions should be listed
	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list effective permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEffectivePermissionsParams) WithDefaults() *ListEffectivePermissionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list effective permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEffectivePermissionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list effective permissions params
func (o *ListEffectivePermissionsParams) WithTimeout(timeout time.Duration) *ListEffectivePermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list effective permissions params
func (o *ListEffectivePermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list effective permissions params
func (o *ListEffectivePermissionsParams) WithContext(ctx context.Context) *ListEffectivePermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list effective permissions params
func (o *ListEffectivePermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list effective permissions params
func (o *ListEffectivePermissionsParams) WithHTTPClient(client *http.Client) *ListEffectivePermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list effective permissions params
func (o *ListEffectivePermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the list effective permissions params
func (o *ListEffectivePermissionsParams) WithUser(user string) *ListEffectivePermissionsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the list effective permissions params
func (o *ListEffectivePermissionsParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *ListEffectivePermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
