// Code generated by go-swagger; DO NOT EDIT.

package users_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListUserPermissionsParams creates a new ListUserPermissionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListUserPermissionsParams() *ListUserPermissionsParams {
	return &ListUserPermissionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListUserPermissionsParamsWithTimeout creates a new ListUserPermissionsParams object
// with the ability to set a timeout on a request.
func NewListUserPermissionsParamsWithTimeout(timeout time.Duration) *ListUserPermissionsParams {
	return &ListUserPermissionsParams{
		timeout: timeout,
	}
}

// NewListUserPermissionsParamsWithContext creates a new ListUserPermissionsParams object
// with the ability to set a context for a request.
func NewListUserPermissionsParamsWithContext(ctx context.Context) *ListUserPermissionsParams {
	return &ListUserPermissionsParams{
		Context: ctx,
	}
}

// NewListUserPermissionsParamsWithHTTPClient creates a new ListUserPermissionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListUserPermissionsParamsWithHTTPClient(client *http.Client) *ListUserPermissionsParams {
	return &ListUserPermissionsParams{
		HTTPClient: client,
	}
}

/*
ListUserPermissionsParams contains all the parameters to send to the API endpoint

	for the list user permissions operation.

	Typically these are written to a http.Request.
*/
type ListUserPermissionsParams struct {

	/* User.

	   The name of the user whose permissions should be listed
	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list user permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUserPermissionsParams) WithDefaults() *ListUserPermissionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list user permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUserPermissionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list user permissions params
func (o *ListUserPermissionsParams) WithTimeout(timeout time.Duration) *ListUserPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list user permissions params
func (o *ListUserPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list user permissions params
func (o *ListUserPermissionsParams) WithContext(ctx context.Context) *ListUserPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list user permissions params
func (o *ListUserPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list user permissions params
func (o *ListUserPermissionsParams) WithHTTPClient(client *http.Client) *ListUserPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list user permissions params
func (o *ListUserPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the list user permissions params
func (o *ListUserPermissionsParams) WithUser(user string) *ListUserPermissionsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the list user permissions params
func (o *ListUserPermissionsParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *ListUserPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
