// Code generated by go-swagger; DO NOT EDIT.

package users_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vshn/stardog-userrole-operator/stardogrest/models"
)

// RemoveUserPermissionReader is a Reader for the RemoveUserPermission structure.
type RemoveUserPermissionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveUserPermissionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewRemoveUserPermissionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRemoveUserPermissionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRemoveUserPermissionCreated creates a RemoveUserPermissionCreated with default headers values
func NewRemoveUserPermissionCreated() *RemoveUserPermissionCreated {
	return &RemoveUserPermissionCreated{}
}

/*
RemoveUserPermissionCreated describes a response with status code 201, with default header values.

Null response
*/
type RemoveUserPermissionCreated struct {
}

// IsSuccess returns true when this remove user permission created response has a 2xx status code
func (o *RemoveUserPermissionCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove user permission created response has a 3xx status code
func (o *RemoveUserPermissionCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove user permission created response has a 4xx status code
func (o *RemoveUserPermissionCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove user permission created response has a 5xx status code
func (o *RemoveUserPermissionCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this remove user permission created response a status code equal to that given
func (o *RemoveUserPermissionCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the remove user permission created response
func (o *RemoveUserPermissionCreated) Code() int {
	return 201
}

func (o *RemoveUserPermissionCreated) Error() string {
	return fmt.Sprintf("[POST /permissions/user/{user}/delete][%d] removeUserPermissionCreated ", 201)
}

func (o *RemoveUserPermissionCreated) String() string {
	return fmt.Sprintf("[POST /permissions/user/{user}/delete][%d] removeUserPermissionCreated ", 201)
}

func (o *RemoveUserPermissionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveUserPermissionDefault creates a RemoveUserPermissionDefault with default headers values
func NewRemoveUserPermissionDefault(code int) *RemoveUserPermissionDefault {
	return &RemoveUserPermissionDefault{
		_statusCode: code,
	}
}

/*
RemoveUserPermissionDefault describes a response with status code -1, with default header values.

unexpected error
*/
type RemoveUserPermissionDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this remove user permission default response has a 2xx status code
func (o *RemoveUserPermissionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this remove user permission default response has a 3xx status code
func (o *RemoveUserPermissionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this remove user permission default response has a 4xx status code
func (o *RemoveUserPermissionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this remove user permission default response has a 5xx status code
func (o *RemoveUserPermissionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this remove user permission default response a status code equal to that given
func (o *RemoveUserPermissionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the remove user permission default response
func (o *RemoveUserPermissionDefault) Code() int {
	return o._statusCode
}

func (o *RemoveUserPermissionDefault) Error() string {
	return fmt.Sprintf("[POST /permissions/user/{user}/delete][%d] removeUserPermission default  %+v", o._statusCode, o.Payload)
}

func (o *RemoveUserPermissionDefault) String() string {
	return fmt.Sprintf("[POST /permissions/user/{user}/delete][%d] removeUserPermission default  %+v", o._statusCode, o.Payload)
}

func (o *RemoveUserPermissionDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *RemoveUserPermissionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
